Update checks for hidden command
JannatinNaim/Kryfios pull request #1
Opened 2021-08-13 16:30 UTC by touhidurrr

2021-08-13 16:46 UTC, JannatinNaim commented
I think you didn't get the point of the checks at [#L310](https://github.com/JannatinNaim/Kryfios/blob/main/src/modules/command.js#L310) and [#L322](https://github.com/JannatinNaim/Kryfios/blob/main/src/modules/command.js#L322). The roles and permissions are checked even if the command is hidden or not. 

The `!hidden` checks if the command is hidden or not. If the command is hidden, it doesn't send a reply saying that the command is not available to the user. 
NOTE: There should be a return statement in an `else` section after those checks. That way the execution of the command stops if the permissions are not met and the command is hidden.

2021-08-13 16:50 UTC, JannatinNaim commented on src/modules/command.js
> -
Keep this as it is. Revert back to the previous commit and leave them be.

2021-08-13 16:51 UTC, JannatinNaim commented on src/modules/command.js
> -		}
After this check, put an `else` statement that returns from the function. As the user doesn't have the permissions and the command is hidden, we don't want it to run any further.

2021-08-13 16:53 UTC, JannatinNaim requested changes
[Pull Request Review Comment](https://github.com/JannatinNaim/Kryfios/pull/1#issuecomment-898590882)

Address those issues put in the comment of the changed and the comment above.

2021-08-13 18:31 UTC, touhidurrr commented on src/modules/command.js
> -		}
there is no need for that as I can see.
If the users doesn't have permissions of role the the bot send a message and exits from handleCommands with return.
There is no need for an else statement.
Cause otherwise bot would through no error and execute as it is.

2021-08-13 18:32 UTC, touhidurrr commented on src/modules/command.js
> -		}
Also you can visit https://github.com/touhidurrr/Kryfios/edit/main/src/modules/command.js and pr and those prs will be automatically added in this pr.

2021-08-13 18:34 UTC, touhidurrr reviewed
Reveiw. Unnecessary suggesstions.

2021-08-13 23:58 UTC, JannatinNaim submitted a review, later dismissed
The idea of allowing the command to run if the user has either the roles or permissions seems to be a nice idea. So, it's okay. But as I said, the checks for hidden command are there to prevent error messages from appearing. So, just return from the function if the user doesn't have the permissions and don't send an error message.

2021-08-13 23:58 UTC, JannatinNaim commented on src/modules/command.js
> -		}
You're not getting the point there. Let me explain.

If the command has fields for `requiredPermissions`, it will check for the permissions. If there are no permissions, it will still perform that check because passing an empty array to `message.member.permissions.has()` will return true. If the user does have the permissions, we skip [#L310](https://github.com/JannatinNaim/Kryfios/blob/main/src/modules/command.js#L310) to [#L320](https://github.com/JannatinNaim/Kryfios/blob/main/src/modules/command.js#L310). But, if the user doesn't have the permissions, we check if the command is `hidden` or not. If it is, we don't display the error message and should immediately return from the function, hence the `else` statement is needed.

NOTE: A `hidden` command is a command that is available in the source files but isn't displayed in the help menu or send error messages if the user trying to access the command doesn't have the permissions to do so.

2021-08-14 15:26 UTC, JannatinNaim commented
> The idea of allowing the command to run if the user has either the roles or permissions seems to be a nice idea. So, it's okay. But as I said, the checks for hidden command are there to prevent error messages from appearing. So, just return from the function if the user doesn't have the permissions and don't send an error message.

Now that I think about it, it's not that great of a feature. Some commands I only want to be accessible to the ADMINISTRATOR of the server (even if they don't have any roles). So, scrap that feature.

2021-08-14 15:39 UTC, JannatinNaim commented
Issues fixed regarding handling of hidden commands and command permissions in commit [#c32461ce](https://github.com/JannatinNaim/Kryfios/commit/001c58804847c4ac1ddaf4bb401eb95c69c83069)

2021-08-14 15:39 UTC, closed without merging